# Read the Docs configuration file for torch_amt
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.14"
  jobs:
    post_install:
      - echo "torch_amt installed successfully"

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Documentation formats (HTML only)
formats:
  - htmlzip
